# Generated by Django 4.2.9 on 2024-06-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_alter_transportorder_parcel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='courier',
            field=models.CharField(choices=[('ไปรษณีย์ไทย', 'ไปรษณีย์ไทย'), ('Shopee express', 'Shopee express'), ('Kerry Express', 'Kerry Express'), ('BEST EXPRESS', 'BEST EXPRESS'), ('J&T EXPRESS', 'J&T EXPRESS'), ('FLASH EXPRESS', 'FLASH EXPRESS'), ('DHL EXPRESS', 'DHL EXPRESS'), ('ยกเลิกคำสั่งซื้อ', 'ยกเลิกคำสั่งซื้อ')], max_length=20),
        ),
    ]
