# Generated by Django 4.2.9 on 2025-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_notebook_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mousekeyboard',
            name='brand',
            field=models.CharField(choices=[('Logitech', 'Logitech'), ('Razer', 'Razer'), ('SteelSeries', 'SteelSeries'), ('Corsair', 'Corsair'), ('ASUS', 'ASUS'), ('HP', 'HP'), ('Dell', 'Dell'), ('Microsoft', 'Microsoft'), ('Cooler Master', 'Cooler Master'), ('HyperX', 'HyperX'), ('Zowie', 'Zowie'), ('Anitech', 'Anitech')], max_length=50),
        ),
    ]
