# Generated by Django 4.2.9 on 2025-01-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_mousekeyboard_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphonespeakers',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50),
        ),
    ]
